In [1]:
import geopandas as gpd
from shapely import wkb
from requests import get

http_proxy = "http://intranet.ise.fhg.de:3128"
https_proxy = "https://intranet.ise.fhg.de:3128"

proxies = {
    "http": http_proxy,
    "https": https_proxy,
}

version = 'v0.4.5' # latest run eGo Dataprocessing
# today: 22.05.04

# all hs/ms substation
hvmv_subst = get('https://openenergy-platform.org/api/v0/schema/grid/tables/ego_dp_hvmv_substation/rows/?where=version='+version, verify=False)  # , proxies=proxies
gdf_hvmv_subst = gpd.GeoDataFrame(hvmv_subst.json())
gdf_hvmv_subst['geom'] = gdf_hvmv_subst['geom'].apply(lambda x: wkb.loads(x, hex=True))
gdf_hvmv_subst = gdf_hvmv_subst.set_geometry('geom')
gdf_hvmv_subst.crs = 'epsg:3035'

C:\Users\johnr\anaconda3\envs\ding0\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openenergy-platform.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

In [5]:
print(len(gdf_hvmv_subst))
gdf_hvmv_subst.head(7)

3591

,version,subst_id,lon,lat,point,polygon,voltage,power_type,substation,osm_id,osm_www,frequency,subst_name,ref,operator,dbahn,status,otg_id,ags_0,geom
0,v0.4.5,1,9.590535,47.753704,01010000000547B88B5A2E2340EA6E825F79E04740,01030000000100000008000000831F35E2052E2340C2CA...,110000,substation,NA,w102614597,http://www.osm.org/way/102614597,NA,NA,NA,NA,no,2,26096,08436064,POINT (4290279.906 2737872.968)
1,v0.4.5,2,9.562066,47.684396,0101000000D7FC5A11C71F2340499FC7459AD74740,0103000000010000000B000000ED0198FA101F23400FC7...,110000,substation,transmission,w102625864,http://www.osm.org/way/102625864,50,Umspannwerk Buch,NA,EnBW,no,1,26097,08435035,POINT (4288099.752 2730184.007)
2,v0.4.5,3,9.527653,47.672163,0101000000C3E6378F280E234078E8217109D64740,0103000000010000000C00000002227100A50D23406390...,110000,station,NA,w102625868,http://www.osm.org/way/102625868,NA,NA,NA,NA,no,2,28170,08435035,POINT (4285506.092 2728840.742)
3,v0.4.5,4,9.565578,47.618739,0101000000E6143C77932123408E8888D632CF4740,010300000001000000090000005B5AF09846212340DC98...,110000,substation,distribution,w102625878,http://www.osm.org/way/102625878,50,Umspannwerk Langenargen,NA,EnBW Regional AG,no,1,26098,08435030,POINT (4288322.031 2722887.274)
4,v0.4.5,5,9.381225,47.716306,0101000000997128EE2FC32240304CD9EDAFDB4740,01030000000100000006000000E6153B5CDCC222407FEA...,110000,substation,distribution,w102640011,http://www.osm.org/way/102640011,50,UW EnBW Markdorf,NA,EnBW,no,1,26099,08435034,POINT (4274543.051 2733826.713)
5,v0.4.5,6,9.287745,47.697383,01010000003623B9535393224041D195D443D94740,0103000000010000000500000018D25E8E1B9322401292...,110000,substation,distribution,w102640012,http://www.osm.org/way/102640012,50,Umspannwerk Meersburg,NA,NA,no,1,26100,08435036,POINT (4267505.240 2731787.183)
6,v0.4.5,7,9.302449,47.792420,0101000000F00FD5A1DA9A224008414C056EE54740,0103000000010000000600000012038FF3909A2240AC5B...,110000,substation,transmission,w102640013,http://www.osm.org/way/102640013,NA,NA,NA,EnBW,no,2,26101,08435052,POINT (4268706.370 2742336.639)

In [7]:
%%time

gdf_hvmv_subst['cordinates_lon_lat'] = gdf_hvmv_subst.apply(lambda x: [[x.lon, x.lat]], axis=1)
gdf_hvmv_subst['cordinates_lat_lon'] = gdf_hvmv_subst.apply(lambda x: [[x.lat, x.lon]], axis=1)

CPU times: total: 172 ms
Wall time: 187 ms

,version,subst_id,lon,lat,point,polygon,voltage,power_type,substation,osm_id,...,subst_name,ref,operator,dbahn,status,otg_id,ags_0,geom,cordinates_lon_lat,cordinates_lat_lon
0,v0.4.5,1,9.590535,47.753704,01010000000547B88B5A2E2340EA6E825F79E04740,01030000000100000008000000831F35E2052E2340C2CA...,110000,substation,NA,w102614597,...,NA,NA,NA,no,2,26096,08436064,POINT (4290279.906 2737872.968),"[[9.59053455948334, 47.7537040125734]]","[[47.7537040125734, 9.59053455948334]]"